# Generated by Django 4.2.7 on 2023-11-28 07:48

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(validators=[products.models.non_negative_validator]),
        ),
    ]
