# Generated by Django 4.2.7 on 2023-11-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_products_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'category')},
        ),
    ]
