# Generated by Django 4.2.7 on 2023-11-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
