# Generated by Django 4.2.7 on 2023-11-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_storeinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory',
            name='product_name',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products_inventory', to='products.products'),
        ),
    ]
