# Generated by Django 4.2.7 on 2023-11-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_storeinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreInventory',
        ),
    ]
